[[redirects]]
  from = "/article"
  to = "/blog"
  status = 302
  force = true

[[redirects]]
  from = "/articles"
  to = "/blog"
  status = 302
  force = true

[[redirects]]
  from = "/article/react_native_gotchas"
  to = "/react-native-gotchas"
  status = 301
  force = true

[[redirects]]
  from = "/article/stripe_internship"
  to = "/stripe-internship-2018"
  status = 301
  force = true

[[redirects]]
  from = "/article/optimizely_internship"
  to = "/optimizely-internship-2017"
  status = 301
  force = true

[[redirects]]
  from = "/building-a-student-tech-community"
  to = "https://angushtlam.substack.com/p/building-a-student-tech-community"
  status = 301
  force = true
